#!/usr/bin/env bash
# -*- bash -*-
#
#
#
set -u -e -o pipefail



./configure                    \
  --with-luajit                \
  --prefix=/tmp/rest/openresty \
  --with-http_postgres_module  \
  --with-http_iconv_module     \
  --user= \
  --group=
