#!/usr/bin/env bash
# -*- bash -*-
#
#!/usr/bin/env node
# -*- js   -*-
#
#!/usr/bin/env lua
#
#
set -u -e -o pipefail

if [[ -z "$(command -v unzip)" ]]
then
  sudo apt-get install unzip
fi

lua="$(command -v lua)"

if [[ -z "$lua" ]]
then
  echo "!!! FAIL: lua was not found." 1>&2
  exit 1
fi

prefix=$(pwd)
target="$(pwd)/.rocks"
lua_bin="$(dirname $lua)"
lua_prefix="$(dirname $lua_bin)"
lua_h="$(cd $lua_prefix && find "$(pwd)" -name lua.h)"
include_path="$(dirname $lua_h)"

mkdir -p .rocks
cd .rocks
rm -f luarocks-*.tar.gz
base="luarocks-2.1.0"
curl -fsSO http://luarocks.org/releases/$base.tar.gz

tar xzvf $base.tar.gz
cd $base
./configure                      \
  --prefix=$target               \
  --rocks-tree=$target           \
  --with-lua=$lua_prefix         \
  --with-lua-include=$include_path        \
  --force-config

make build
make install

cd $prefix
if [[ -z "$(command -v luarocks)" ]]
then
  echo -e "\n=== Luarocks installed, but not in path."
  echo    "Put this in your path."
  echo    ".rocks/bin"
else
  echo -e "\n=== Installed: $(command -v luarocks)"
fi



